<div id="taxo_lexique" class="wims_widget_box small-12 medium-6 large-4 cell">
    <div class="title_box">
      <h2 class="wims_title">Recherche par programme</h2>
      <!--<br class="clearall" />-->
    </div>
    <div class="box_content">
        <button class="button small dropdown small-dropdown" type="button" data-toggle="index_level_math"><span class="text_icon exomodify"></span>&nbsp;Mathématiques</button>
        <div class="dropdown-pane" data-position="bottom" data-alignment="left" id="index_level_math" data-dropdown data-auto-focus="true">
                <nav class ="summary">
                        <ul  class="dropdown menu vertical medium-horizontal" data-responsive-menu="accordion small-dropdown">
                            <li><a href="#" >Primaire</a>
                                <ul class="menu vertical">
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle1 Cycle 1
                                    </li>
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle2 Cycle 2
                                    </li>
                                </ul>
                            </li>
                            <li><a>Collège</a>
                                <ul class="menu vertical">
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle3 Cycle 3
                                    </li>
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle4 Cycle 4
                                    </li>
                                </ul>
                            </li>
                            <li><a>Lycée</a>
                                <ul class="menu vertical">
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.2 Seconde
                                    </li>
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.1S Première S
                                    </li>
                                    <li>
                                        <a>Terminale</a>
                                    </li>
                                </ul>
                                </li>
                            <li><a>Post-bac</a>
                                <ul class="menu vertical">
                                    <li>
                                        <a>Niveau L1</a>
                                    </li>
                                    <li>
                                        <a>Niveau L2</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                </nav>
        </div>
        <button class="button small dropdown small-dropdown" type="button" data-toggle="level_phy"><span class="text_icon exomodify"></span>&nbsp;Physique</button>
        <div class="dropdown-pane" data-position="bottom" data-alignment="left" id="level_phy" data-dropdown data-auto-focus="true">
                <nav class ="summary">
                        <ul  class="dropdown menu vertical medium-horizontal" data-responsive-menu="accordion small-dropdown">
                            <li><a href="#" >Primaire</a>
                                <ul class="menu vertical">
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle1 Cycle 1
                                    </li>
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle2 Cycle 2
                                    </li>
                                </ul>
                            </li>
                            <li><a>Collège</a>
                                <ul class="menu vertical">
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle3 Cycle 3
                                    </li>
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.cycle4 Cycle 4
                                    </li>
                                </ul>
                            </li>
                            <li><a>Lycée</a>
                                <ul class="menu vertical">
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.2 Seconde
                                    </li>
                                    <li>
                                        !href module=help/teacher/program/&cmd=new&job=math.1S Première S
                                    </li>
                                    <li>
                                        <a>Terminale</a>
                                    </li>
                                </ul>
                                </li>
                            <li><a>Post-bac</a>
                                <ul class="menu vertical">
                                    <li>
                                        <a>Niveau L1</a>
                                    </li>
                                    <li>
                                        <a>Niveau L2</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                </nav>
        </div>
    </div>
</div>

