  !set email=$responsable_math_cycle4
<h2 class="wims_title"> Mathématiques Cycle 4</h2>
<h3 class="wims_title"><a href="https://euler.ac-versailles.fr/IMG/pdf/2016_maths_cycle_4-2.pdf" target="wims_external">BO spécial n°11 du 26 novembre 2015</a></h3>
<div class="wims_msg info program_desc">

Dernière mise à jour : 10-06-2018
</div>
<div>
  
<div>
		<div id="intro" class="accordion">
			<h3>Préambule</h3>
			<div id="preambule">
				<p>Le programme de mathématiques est rédigé pour l'ensemble du cycle. Les connaissances et compétences visées sont des attendus de la fin du cycle. Pour y parvenir, elles devront être travaillées de manière progressive et réinvesties sur toute la durée du cycle. Des repères de progressivité indiquent en particulier quelles notions ne doivent pas être introduites dès le début du cycle, mais seulement après que d'autres notions ont été rencontrées, puis stabilisées.</p>
				<p>Ce programme est ancré dans les cinq domaines du socle et il est structuré selon les quatre thèmes classiques : nombres et calculs ; organisation et gestion de données, fonctions ; grandeurs et mesures ; espace et géométrie. En outre, un enseignement de l'informatique est dispensé conjointement en mathématiques et en technologie. Ces domaines du socle et ces thèmes du programme ne sont évidemment pas étanches.</p>
				<p>La mise en &oelig;uvre du programme doit permettre de développer les six compétences majeures de l'activité mathématique : chercher, modéliser, représenter, raisonner, calculer, communiquer, qui sont détaillées dans le tableau ci-après.</p>
				<p>Pour ce faire, une place importante doit être accordée à la résolution de problèmes, qu'ils soient internes aux mathématiques ou liés à des situations issues de la vie quotidienne ou d'autres disciplines. Le programme fournit des outils permettant de modéliser des situations variées sous forme de problèmes mathématisés.</p>
				<p>La résolution de problèmes nécessite de s'appuyer sur un corpus de connaissances et de méthodes. Les élèves doivent disposer de réflexes intellectuels et d'automatismes tels que le calcul mental, qui, en libérant la mémoire, permettent de centrer la réflexion sur l'élaboration d'une démarche.</p>
				<p>La formation au raisonnement et l'initiation à la démonstration sont des objectifs essentiels du cycle 4. Le raisonnement, au c&oelig;ur de l'activité mathématique, doit prendre appui sur des situations variées (par exemple problèmes de nature arithmétique ou géométrique, mais également mise au point d'un programme qui doit tourner sur un ordinateur ou pratique de jeux pour lesquels il faut développer une stratégie gagnante, individuelle ou collective, ou maximiser ses chances). Les pratiques d'investigation (essai-erreur, conjecture-validation, etc.) sont essentielles et peuvent s'appuyer aussi bien sur des manipulations ou des recherches papier/crayon, que sur l'usage d'outils numériques (tableurs, logiciels de géométrie, etc.). Il est important de ménager une progressivité dans l'apprentissage de la démonstration et de ne pas avoir trop d'exigences concernant le formalisme.</p>
				<p>L'explicitation de la démarche utilisée et la rédaction d'une solution participent au développement des compétences de communication orale et écrite.</p>
				<p>Le programme donne une place importante à l'utilisation des nombres. L'introduction de nouveaux nombres (nombres rationnels, racine carrée) peut utilement s'appuyer sur un travail des grandeurs et mesures ou de la géométrie. L'extension des procédures de calcul (addition, soustraction, multiplication, division) aux nombres rationnels et l'introduction du calcul littéral doivent s'appuyer sur des situations permettant de construire le sens des nombres et des opérations.</p>
				<p>Au cycle 3, l'élève a commencé à passer d'une géométrie où les objets et leurs propriétés sont contrôlés par l'observation et l'instrumentation à une géométrie dont la validation s'appuie sur le raisonnement et l'argumentation. Ces nouvelles formes de validation sont un objectif majeur du cycle 4. En fin de cycle, de nouvelles transformations géométriques sont étudiées à travers des activités de description et de construction, pouvant s'appuyer sur l'utilisation de logiciels.</p>
				<p>Au cycle 4, l'élève développe son intuition en passant d'un mode de représentation à un autre : numérique, graphique, algébrique, géométrique, etc. Ces changements de registre sont favorisés par l'usage de logiciels polyvalents tels que le tableur ou les logiciels de géométrie dynamique. L'utilisation du tableur et de la calculatrice est nécessaire pour gérer des données réelles et permet d'inscrire l'activité mathématique dans les domaines 3, 4 et 5 du socle.</p>
				<p>L'enseignement de l'informatique au cycle 4 n'a pas pour objectif de former des élèves experts, mais de leur apporter des clés de décryptage d'un monde numérique en évolution constante. Il permet d'acquérir des méthodes qui construisent la pensée algorithmique et développe des compétences dans la représentation de l'information et de son traitement, la résolution de problèmes, le contrôle des résultats. Il est également l'occasion de mettre en place des modalités d'enseignement fondées sur une pédagogie de projet, active et collaborative. Pour donner du sens aux apprentissages et valoriser le travail des élèves, cet enseignement doit se traduire par la réalisation de productions collectives (programme, application, animation, sites, etc.) dans le cadre d'activités de création numérique, au cours desquelles les élèves développent leur autonomie, mais aussi le sens du travail collaboratif.</p>
				<p>La pratique des mathématiques, en particulier les activités de recherche, amène les élèves à travailler sur des notions ou des objets mathématiques dont la maîtrise n'est pas attendue en fin de troisième (par exemple, irrationalité de certains nombres, caractéristiques de dispersion d'une série statistique autres que l'étendue, modélisation de phénomènes aléatoires, calculs de distances astronomiques, droites remarquables dans un triangle, travail sur les puissances et capacité de stockage) ; c'est aussi l'occasion d'enrichir leur culture scientifique.</p>
			</div>

	    	<h3>Compétences travaillées et domaines du socle</h3>
			<div id="competence">
				<table class="wimsborder blockcenter">
					<thead>
						<tr>
							<th class="contenu" style="width:90%">Compétences travaillées</th>
							<th class="modalites" style="width:10%">Domaines du socle</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="program_contenu">
								Chercher
								<ul class="wims_summary">
									<li>
										Extraire d'un document les informations utiles, les reformuler, les organiser, les confronter à ses connaissances.
									</li>
									<li>
										S'engager dans une démarche scientifique, observer, questionner, manipuler, expérimenter (sur une feuille de papier, avec des objets, à l'aide de logiciels), émettre des hypothèses, chercher des exemples ou des contre-exemples, simplifier ou particulariser une situation, émettre une conjecture.
									</li>
									<li>Tester, essayer plusieurs pistes de résolution.</li>
									<li>Décomposer un problème en sous-problèmes.</li>
								</ul>
							</td>
							<td class="program_modalites">2, 4</td>
						</tr>
						<tr>
							<td class="program_contenu">
								Modéliser
								<ul class="wims_summary">
									<li>
										Reconnaître des situations de proportionnalité et résoudre les problèmes correspondants.
									</li>
									<li>
										Traduire en langage mathématique une situation réelle (par exemple à l'aide d'équations, de fonctions, de configurations géométriques, d'outils statistiques).
									</li>
									<li>
										Comprendre et utiliser une simulation numérique ou géométrique.
									</li>
									<li>
										Valider ou invalider un modèle, comparer une situation à un modèle connu (par exemple un modèle aléatoire).
									</li>
								</ul>
							</td>
							<td class="program_modalites">1, 2, 4</td>
						</tr>
						<tr>
							<td class="program_contenu">
								Représenter
								<ul class="wims_summary">
									<li>
										Choisir et mettre en relation des cadres (numérique, algébrique, géométrique) adaptés pour traiter un problème ou pour étudier un objet mathématique.
									</li>
									<li>Produire et utiliser plusieurs représentations des nombres.</li>
									<li>Représenter des données sous forme d'une série statistique.</li>
									<li>
										Utiliser, produire et mettre en relation des représentations de solides (par exemple perspective ou vue de dessus/de dessous) et de situations spatiales (schémas, croquis, maquettes, patrons, figures géométriques, photographies, plans, cartes, courbes de niveau).
									</li>
								</ul>
							</td>
							<td class="program_modalites">1, 5</td>
						</tr>
						<tr>
							<td class="program_contenu">
								Raisonner
								<ul>
									<li>
										Résoudre des problèmes impliquant des grandeurs variées (géométriques, physiques, économiques) : mobiliser les connaissances nécessaires, analyser et exploiter ses erreurs, mettre à l'essai plusieurs solutions.
									</li>
									<li>
										Mener collectivement une investigation en sachant prendre en compte le point de vue d'autrui.
									</li>
									<li>
										Démontrer : utiliser un raisonnement logique et des règles établies (propriétés, théorèmes, formules) pour parvenir à une conclusion.
									</li>
									<li>
										Fonder et défendre ses jugements en s'appuyant sur des résultats établis et sur sa maîtrise de l'argumentation.
									</li>
								</ul>

							</td>
							<td class="program_modalites">2, 3, 4</td>
						</tr>
						<tr>
							<td class="program_contenu">
								Calculer
								<ul>
									<li>
										Calculer avec des nombres rationnels, de manière exacte ou approchée, en combinant de façon appropriée le calcul mental, le calcul posé et le calcul instrumenté (calculatrice ou logiciel).
									</li>
									<li>
										Contrôler la vraisemblance de ses résultats, notamment en estimant des ordres de grandeur ou en utilisant des encadrements.
									</li>
									<li>
										Calculer en utilisant le langage algébrique (lettres, symboles, etc...).
									</li>
								</ul>

							</td>
							<td class="program_modalites">4</td>
						</tr>
						<tr>
							<td class="program_contenu">
								Communiquer
								<ul>
									<li>
										Faire le lien entre le langage naturel et le langage algébrique. Distinguer des spécificités du langage mathématique par rapport à la langue française.
									</li>
									<li>
										Expliquer à l'oral ou à l'écrit (sa démarche, son raisonnement, un calcul, un protocole de construction géométrique, un algorithme), comprendre les explications d'un autre et argumenter dans l'échange.
									</li>
									<li>
										Vérifier la validité d'une information et distinguer ce qui est objectif et ce qui est subjectif ; lire, interpréter, commenter, produire des tableaux, des graphiques, des diagrammes.
									</li>
								</ul>

							</td>
							<td class="program_modalites">1, 3</td>
						</tr>
					</tbody>
				</table>
			</div>
    </div>
</div>
		<div class="wimscenter">
			<a class="external_link" href="https://euler.ac-versailles.fr/article21.html" target="wims_external" title="Ressources complémentaires sur le site Euler">Ressources complémentaires</a>
		</div>
</div>
<div id="widget_mathcycle4">
<ul class="wims_summary">
<li><a href="#c_0">Nombres et calculs</a></li><li><a href="#c_4">Organisation et gestion de données, fonctions</a></li><li><a href="#c_9">Grandeurs et mesures</a></li><li><a href="#c_12">Espace et géométrie</a></li><li><a href="#c_15">Algorithmique et programmation</a></li><li><a href="#c_17">Croisements entre enseignements</a></li></ul>

<div id="c_0"><h3 class="program_theme">Nombres et calculs</h3>
    <div class="accordion">
      <h4>Présentation</h4>
      <div>
Au cycle 4, les élèves consolident le sens des nombres et confortent la maitrise
des procédures de calcul. Les différentes composantes de ce thème sont reliées
entre elles. Les élèves manipulent des nombres rationnels de signe quelconque.
Ils prennent conscience du fait qu'un même nombre peut avoir plusieurs écritures
(notamment écritures fractionnaire et décimale). Les élèves abordent les bases
du calcul littéral, qu'ils mettent en &oelig;uvre pour résoudre des problèmes
faisant intervenir des équations ou inéquations du premier degré. A l'occasion
d'activités de recherche, ils peuvent rencontrer la notion de nombres
irrationnels, par exemple lors d'un travail sur les racines carrées.</div>
    </div>

<h4></h4><ul class="program_submenu"><li><a href="#c_1">Utiliser les nombres pour comparer, calculer et résoudre des problèmes</a></li><li><a href="#c_2">Comprendre et utiliser les notions de divisibilité et de nombres premiers</a></li><li><a href="#c_3">Utiliser le calcul littéral</a></li></ul><div id="c_1"><h4 class="program_titre">Utiliser les nombres pour comparer, calculer et résoudre des problèmes</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Utiliser diverses représentations d'un même nombre
(écriture décimale ou fractionnaire, notation scientifique,
repérage sur une droite graduée) ;
passer d'une représentation à une autre.
<ul><li>	Nombres décimaux.
</li><li>Nombres rationnels (positifs ou négatifs), notion d'opposé.
</li><li>Fractions, fractions irréductibles, cas particulier des fractions décimales.
</li><li>Définition de la racine carrée ; les carrés parfaits entre 1 et 144.
</li><li>Les préfixes de nano à giga.
</li></ul></td>
<td class="program_modalites">Rencontrer diverses écritures dans des situations variées (par exemple nombres
décimaux dans des situations de vie quotidienne, notation scientifique en
physique, nombres relatifs pour mesurer des températures ou des altitudes).
<p>
Relier fractions, proportions et pourcentages.
</p><p>
Associer à des objets des ordres de grandeurs (par exemple la
taille d'un atome, d'une bactérie, d'une alvéole pulmonaire, la longueur de
l'intestin, la capacité de stockage d'un disque dur, la vitesse du son et de la
lumière, la population française et mondiale, la distance de la Terre à la Lune
et au Soleil, la distance du Soleil à l'étoile la plus proche).
</p><p>
Prendre conscience que certains nombres ne sont pas rationnels.
</p></td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">Comparer, ranger, encadrer des nombres rationnels.
  <br class="spacer">Repérer et placer un nombre rationnel sur une droite graduée.
  <ul><li>Ordre sur les nombres rationnels en écriture décimale ou fractionnaire.
  </li><li>Égalité de fractions.
  </li></ul></td>
<td class="program_modalites">Montrer qu'il est toujours possible d'intercaler des rationnels
  entre deux rationnels donnés, contrairement au cas des entiers.</td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!set wims_ref_class=text_icon icon_quizz
!set wims_ref_title=Comparer 5 nombres rationnels donnés
!href target=wims_exo module=H2/algebra/oefrationnel.fr&exo=n2s1e06&+cmd=new Ranger des fractions
</li> </ul>
</td></tr><tr><td class="program_contenu"><p>Pratiquer le calcul exact ou
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/analysis/fr/approx_val0&+cmd=new approché
, mental, à la main ou instrumenté.
</p><p>Calculer avec des nombres relatifs, des fractions ou des nombres décimaux
(somme, différence, produit, quotient).
</p><p>Vérifier la vraisemblance d'un résultat, notamment en estimant son ordre de grandeur.
</p><p>
Effectuer des calculs numériques simples impliquant des puissances, notamment
en utilisant
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/analysis/fr/scientific_notation&+cmd=new la notation scientifique.
</p><p>Définition des
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/algebra/fr/power&+cmd=new puissances d'un nombre
 (exposants entiers, positifs ou négatifs).
</p></td>
<td class="program_modalites">Pratiquer régulièrement le calcul mental ou à la main, et utiliser à bon escient la calculatrice ou un logiciel.
<br class="spacer">Effectuer des calculs et des comparaisons pour traiter des problèmes (par exemple comparer des consommations d'eau ou d'électricité, calculer un indice de masse corporelle pour évaluer un risque éventuel sur la santé, déterminer le nombre d'images pouvant être stockées sur une clé USB, calculer et comparer des taux de croissance démographique).</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_2"><h4 class="program_titre">Comprendre et utiliser les notions de divisibilité et de nombres premiers</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Déterminer si un entier est ou n'est pas multiple ou diviseur d'un autre entier.
<br class="spacer">Simplifier une fraction donnée pour la rendre irréductible.
<ul><li>
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/arithmetic/fr/euclidean_division Division euclidienne
  (quotient, reste).
</li><li>
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/arithmetic/fr/multiple&+cmd=new Multiples
 et diviseurs.
</li><li>Notion de
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/arithmetic/fr/primes&+cmd=new nombres premiers.
</li></ul></td>
<td class="program_modalites"><p>Recourir à une décomposition en facteurs premiers dans des cas simples.
</p><p>
Exploiter tableurs, calculatrices et logiciels, par exemple pour chercher les diviseurs d'un nombre ou déterminer si un nombre est premier.
</p><p>
Démontrer des
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/arithmetic/fr/divisibility_critere&+cmd=new critères de divisibilité
 (par exemple par 2, 3, 5 ou 10) ou la preuve par 9.
</p><p>
Etudier des problèmes d'engrenages (par exemple braquets d'un vélo, rapports de
transmission d'une boîte de vitesses, horloge), de conjonction de phénomènes
périodiques (par exemple éclipses ou alignements de planètes).
</p></td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!set wims_ref_class=text_icon icon_calculator
!set wims_ref_title=Déterminer la liste des diviseurs d'un nombre donné
!href target=wims_exo module=H3/arithmetic/oefarith.fr&exo=listdiv&+cmd=new Liste de diviseurs
</li> </ul>
</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_3"><h4 class="program_titre">Utiliser le calcul littéral</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Mettre un problème en équation en vue de sa résolution.
<br class="spacer">Développer et factoriser des expressions algébriques dans des cas très simples.
<br class="spacer">Résoudre des équations ou des inéquations du premier degré.
<ul><li>Notions de variable, d'inconnue.
</li></ul>
Utiliser le calcul littéral pour prouver un résultat général, pour valider ou réfuter une conjecture.</td>
<td class="program_modalites">Comprendre l'intérêt d'une écriture littérale en produisant et employant des formules liées aux grandeurs mesurables (en mathématiques ou dans d'autres disciplines).
<br class="spacer">Tester sur des valeurs numériques une égalité littérale pour appréhender la notion d'équation.
<br class="spacer">Etudier des problèmes qui se ramènent au premier degré (par exemple, en factorisant des équations produits simples à l'aide d'identités remarquables).
<br class="spacer">Montrer des résultats généraux, par exemple que la somme de trois nombres consécutifs est divisible par 3.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table>
        </div> <!-- close titre -->
      <div class="accordion">
        <h4>Repères de progressivité</h4>
        <div>
La maitrise des techniques opératoires et l'acquisition du sens des nombres et
des opérations appréhendés au cycle 3 sont consolidées tout au long du cycle 4.
<p>
Les élèves rencontrent dès le début du cycle 4 le nombre relatif qui rend possible
toutes les soustractions. Ils généralisent l'addition et la soustraction dans
ce nouveau cadre et rencontrent la notion d'opposé. Puis ils passent au produit
et au quotient, et, quand ces notions ont été bien installées, ils font le lien
avec le calcul littéral.
</p><p>
Au cycle 3, les élèves ont rencontré des fractions simples sans leur donner
le statut de nombre. Dès le début du cycle 4, les élèves construisent et
mobilisent la fraction comme nombre qui rend toutes les divisions possibles.
En 5<sup>e</sup>, les élèves calculent et comparent proportions et fréquences,
justifient par un raisonnement l'égalité de deux quotients, reconnaissent
un nombre rationnel. À partir de la 4<sup>e</sup>, ils sont conduits
à additionner, soustraire, multiplier et diviser des quotients, à passer
d'une représentation à une autre d'un nombre, à justifier qu'un nombre est
ou non l'inverse d'un autre. Ils n'abordent la notion de fraction irréductible
qu'en 3<sup>e</sup>.
</p><p>
La notion de racine carrée est introduite en lien avec le théorème de Pythagore
ou l'agrandissement des surfaces. Les élèves connaissent quelques carrés
parfaits, les utilisent pour encadrer des racines par des entiers et utilisent
la calculatrice pour donner une valeur exacte ou approchée de la racine carrée
d'un nombre positif.
</p><p>
Les puissances de 10 d'exposant entier positif sont manipulées dès la
4<sup>e</sup>, en lien avec les problèmes scientifiques ou technologiques. Les
exposants négatifs sont introduits progressivement. Les puissances positives de
base quelconque sont envisagées comme raccourci d'un produit.
</p><p>
Dès le début du cycle 4, les élèves comprennent l'intérêt d'utiliser une
écriture littérale. Ils apprennent à tester une égalité en attribuant des
valeurs numériques au nombre désigné par une lettre qui y figure. A partir de la
4<sup>e</sup>, ils rencontrent les notions de variables et d'inconnues, la
factorisation, le développement et la réduction d'expressions algébriques. Ils
commencent à résoudre, de façon exacte ou approchée, des problèmes du 1er degré
à une inconnue et apprennent à modéliser une situation à l'aide d'une formule,
d'une équation ou d'une inéquation. En 3<sup>e</sup>, ils résolvent
algébriquement équations et inéquations du 1er degré et mobilisent le calcul
littéral pour démontrer. Ils font le lien entre forme algébrique et
représentation graphique.
</p></div>
      </div>
</div> <!-- close theme -->
<div id="c_4"><h3 class="program_theme">Organisation et gestion de données, fonctions</h3>
    <div class="accordion">
      <h4>Présentation</h4>
      <div>

La plupart des notions travaillées dans ce thème ont déjà été abordées aux cycles précédents. Au cycle 4, les élèves apprennent à utiliser une représentation adaptée de données pour en faire une interprétation critique. Ils abordent les notions d'incertitude et de hasard, afin de construire une citoyenneté critique et rationnelle. Ils apprennent à choisir une méthode adaptée au problème de proportionnalité auquel ils sont confrontés. Ils découvrent progressivement la notion de fonction, qui leur permet d'accéder à de nouvelles catégories de problèmes.</div>
    </div>

<h4></h4><ul class="program_submenu"><li><a href="#c_5">Interpréter, représenter et traiter des données</a></li><li><a href="#c_6">Comprendre et utiliser des notions élémentaires de probabilités</a></li><li><a href="#c_7">Résoudre des problèmes de proportionnalité</a></li><li><a href="#c_8">Comprendre et utiliser la notion de fonction</a></li></ul><div id="c_5"><h4 class="program_titre">Interpréter, représenter et traiter des données</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Recueillir des données, les organiser.
<br class="spacer">Lire des données sous forme de données brutes, de tableau, de graphique.
<br class="spacer">Calculer des effectifs, des fréquences.
<ul><li>Tableaux, représentations graphiques (diagrammes en bâtons, diagrammes circulaires, histogrammes).</li></ul>
Calculer et interpréter des caractéristiques de position ou de dispersion d'une série statistique.
<ul><li>Indicateurs : moyenne, médiane, étendue.</li></ul></td>
<td class="program_modalites">Utiliser un tableur, un grapheur pour calculer des indicateurs et représenter graphiquement les données.
<br class="spacer">Porter un regard critique sur des informations chiffrées, recueillies, par exemple, dans des articles de journaux ou sur des sites web.
<br class="spacer">Organiser et traiter des résultats issus de mesures ou de calculs (par exemple des données mises sur l'environnement numérique de travail par les élèves dans d'autres disciplines) ; questionner la pertinence de la façon dont les données sont collectées.
<br class="spacer">Lire, interpréter ou construire un diagramme dans un contexte économique, social ou politique : résultats d'élections, données de veille sanitaire (par exemple consultations, hospitalisations, mortalité pour la grippe), données financières relatives aux ménages (par exemple impôts, salaires et revenus), données issues de l'étude d'un jeu, d'une &oelig;uvre d'art...</td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!set wims_ref_class=text_icon icon_notebook
!set wims_ref_title=Cours de statistiques
!href target=wims_exo module=H3/stat/docstat.fr&exo=&+cmd=intro Un cours de statistiques
</li> <li>
!set wims_ref_title=Module de 13 exercices de statistiques
!href target=wims_exo module=H3/stat/oefstat.fr&exo=&+cmd=intro Module de statistiques
</li> </ul>
</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_6"><h4 class="program_titre">Comprendre et utiliser des notions élémentaires de probabilités</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Aborder les questions relatives au hasard à partir de problèmes simples.
<br class="spacer">Calculer des probabilités dans des cas simples.
<ul><li>
  Notion de probabilité.
</li><li>
  Quelques propriétés : la probabilité d'un événement est comprise entre 0 et 1 ;
probabilité d'évènements certains, impossibles, incompatibles, contraires.
</li></ul></td>
<td class="program_modalites">Faire le lien entre fréquence et probabilité, en constatant matériellement le phénomène de stabilisation des fréquences ou en utilisant un tableur pour simuler une expérience aléatoire (à une ou à deux épreuves).
<br class="spacer">Exprimer des probabilités sous diverses formes (décimale, fractionnaire, pourcentage).
<br class="spacer">Calculer des probabilités dans un contexte simple (par exemple, évaluation des chances de gain dans un jeu et choix d'une stratégie).</td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!set wims_ref_title=Lien entre un événement et sa probabilité
!href target=wims_exo module=H3/probability/oefstatproba.fr&exo=dailly1&+cmd=new Vocabulaire des probabilités
</li> </ul>
</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_7"><h4 class="program_titre">Résoudre des problèmes de proportionnalité</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Reconnaitre une situation de proportionnalité ou de non-proportionnalité.</td>
<td class="program_modalites">Etudier des relations entre deux grandeurs mesurables pour identifier si elles sont proportionnelles ou non ; ces relations peuvent être exprimées par :
<ul><li>
des formules (par exemple la longueur d'un cercle ou l'aire d'un disque comme
fonction du rayon, la loi d'Ohm exprimant la tension comme fonction de
l'intensité) ;
</li><li>
des représentations graphiques (par exemple des nuages de points ou des courbes) ;
</li><li>
un tableau (dont des lignes ou des colonnes peuvent être proportionnelles ou non).
</li></ul></td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">Résoudre des problèmes de recherche de quatrième proportionnelle.
<br class="spacer">Résoudre des problèmes de pourcentage.
<ul><li>Coefficient de proportionnalité.</li></ul></td>
<td class="program_modalites">Compléter un tableau de proportionnalité en utilisant, par exemple, le produit en croix.
<br class="spacer">Calculer et interpréter des proportions (notamment sous forme de pourcentages) sur des données économiques ou sociales ; appliquer des pourcentages (par exemple taux de croissance, remise, solde, taux d'intérêt) à de telles données.
<br class="spacer">Etablir le fait que, par exemple, augmenter de 5% c'est multiplier par 1,05 et diminuer de 5% c'est multiplier par 0,95 ; proposer quelques applications (par exemple que l'on n'additionne pas les remises).</td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!set wims_ref_title=Module de 22 exercices sur la proportionnalité
!href target=wims_exo module=H1/algebra/oefprop.fr&exo=&+cmd=intro Problèmes sur la proportionnalité
</li> </ul>
</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_8"><h4 class="program_titre">Comprendre et utiliser la notion de fonction</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Modéliser des phénomènes continus par une fonction.
<br class="spacer">Résoudre des problèmes modélisés par des fonctions (équations, inéquations).
<ul><li>Dépendance d'une grandeur mesurable en fonction d'une autre.
</li><li>Notion de variable mathématique.
</li><li>Notion de fonction, d'antécédent et d'image.
</li><li>Notations \(f(x)\) et \(x \mapsto f(x)\).
</li><li>Cas particulier d'une fonction linéaire, d'une fonction affine.
</li></ul></td>
<td class="program_modalites">Utiliser différents modes de représentation et passer de l'un à l'autre,
par exemple en utilisant un tableur ou un grapheur.
<br class="spacer">Lire et interpréter graphiquement les coefficients d'une fonction affine
représentée par une droite.
<br class="spacer">Etudier et commenter des exemples (fonction reliant la tension
et l'intensité dans un circuit électrique, fonction reliant puissance et énergie,
courbes de croissance dans un carnet de santé, tests d'effort, consommation
de carburant d'un véhicule en fonction de la vitesse, production de céréales
en fonction des surfaces ensemencées, liens entre unités anglo-saxonnes et françaises,
impôts et fonctions affines par morceaux...).
<br class="spacer">Faire le lien entre fonction linéaire et proportionnalité.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table>
        </div> <!-- close titre -->
      <div class="accordion">
        <h4>Repères de progressivité</h4>
        <div>
Les caractéristiques de position d'une série statistique sont introduites dès le début du cycle. Les élèves rencontrent des caractéristiques de dispersion à partir de la 4<sup>e</sup>.
<br class="spacer">Les activités autour de la proportionnalité prolongent celles du cycle 3. Au fur et à mesure de l'avancement du cycle, les élèves diversifient les points de vue en utilisant les représentations graphiques et le calcul littéral. En 3<sup>e</sup>, les élèves sont en mesure de faire le lien entre proportionnalité, fonctions linéaires, théorème de Thalès et homothéties et peuvent choisir le mode de représentation le mieux adapté à la résolution d'un problème.
<br class="spacer">En 5<sup>e</sup>, la rencontre de relations de dépendance entre grandeurs mesurables, ainsi que leurs représentations graphiques, permet d'introduire la notion de fonction qui est stabilisée en 3<sup>e</sup>, avec le vocabulaire et les notations correspondantes.
<br class="spacer">Dès le début et tout au long du cycle 4 sont abordées des questions relatives au hasard, afin d'interroger les représentations initiales des élèves, en partant de situations issues de la vie quotidienne (jeux, achats, structures familiales, informations apportées par les médias, etc.), en suscitant des débats. On introduit et consolide ainsi petit à petit le vocabulaire lié aux notions élémentaires de probabilités (expérience aléatoire, issue, probabilité). Les élèves calculent des probabilités en s'appuyant sur des conditions de symétrie ou de régularité qui fondent le modèle équiprobable. Une fois ce vocabulaire consolidé, le lien avec les statistiques est mis en &oelig;uvre en simulant une expérience aléatoire, par exemple sur un tableur. A partir de la 4<sup>e</sup>, l'interprétation fréquentiste permet d'approcher une probabilité inconnue et de dépasser ainsi le modèle d'équiprobabilité mis en &oelig;uvre en 5<sup>e</sup>.</div>
      </div>
</div> <!-- close theme -->
<div id="c_9"><h3 class="program_theme">Grandeurs et mesures</h3>
    <div class="accordion">
      <h4>Présentation</h4>
      <div>
En continuité avec le travail engagé au cycle 3, ce thème se prête particulièrement à des connexions avec les autres thèmes du programme et offre de nombreux liens avec la physique-chimie ou les sciences de la vie et de la Terre. C'est aussi l'occasion d'activités de recherche (par exemple pour déterminer la formule donnant le volume de certains solides).
<br class="spacer">Les élèves doivent disposer de références concrètes (savoir, par exemple, que la circonférence de la Terre est environ 40000 km) et être capables d'estimer l'ordre de grandeur d'une mesure. Par ailleurs, le travail autour des formules s'inscrit parfaitement dans l'introduction du calcul littéral.</div>
    </div>

<h4></h4><ul class="program_submenu"><li><a href="#c_10">Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées</a></li><li><a href="#c_11">Comprendre l'effet de quelques transformations sur des grandeurs géométriques</a></li></ul><div id="c_10"><h4 class="program_titre">Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Mener des calculs impliquant des grandeurs mesurables, notamment des grandeurs composées, en conservant les unités.
<br class="spacer">Vérifier la cohérence des résultats du point de vue des unités.
<ul><li>Notion de grandeur produit et de grandeur quotient.
</li><li>Formule donnant
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/geometry/fr/pyram_vol&+cmd=new le volume d'une pyramide
, d'un cylindre, d'un cône ou d'une boule.</li></ul></td>
<td class="program_modalites">Identifier des grandeurs composées rencontrées en mathématiques ou dans d'autres disciplines (par exemple aire, volume, vitesse, allure, débit, masse volumique, concentration, quantité d'information, densité de population, rendement d'un terrain).
<br class="spacer">Commenter des documents authentiques (par exemple factures d'eau ou d'électricité, bilan sanguin).</td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!set wims_ref_class=text_icon icon_Modules de 9 exercices
!href target=wims_exo module=H3/algebra/oefvitesse.fr&exo=&+cmd=intro Vitesses et aires et volumes de planètes
</li> </ul>
</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_11"><h4 class="program_titre">Comprendre l'effet de quelques transformations sur des grandeurs géométriques</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Comprendre l'effet d'un déplacement, d'un agrandissement ou d'une réduction sur les longueurs, les aires, les volumes ou les angles.
<ul><li>Notion de dimension et rapport avec les unités de mesure (m, m<sup>2</sup>, m<sup>3</sup>).</li></ul></td>
<td class="program_modalites">Utiliser un rapport de réduction ou d'agrandissement (architecture, maquettes), l'échelle d'une carte.
<br class="spacer">Utiliser un système d'information géographique (cadastre, géoportail, etc.) pour déterminer une mesure de longueur ou d'aire ; comparer à une mesure faite directement à l'écran.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table>
        </div> <!-- close titre -->
      <div class="accordion">
        <h4>Repères de progressivité</h4>
        <div>
Le travail sur les grandeurs mesurables et les unités de mesure, déjà entamé au cycle 3, est poursuivi tout au long du cycle 4, en prenant appui sur des contextes issus d'autres disciplines ou de la vie quotidienne. Les grandeurs produits et les grandeurs quotients sont introduites dès la 4<sup>e</sup>. L'effet d'un déplacement, d'un agrandissement ou d'une réduction sur les grandeurs géométriques est travaillé en 3<sup>e</sup>, en lien avec la proportionnalité, les fonctions linéaires et le théorème de Thalès.</div>
      </div>
</div> <!-- close theme -->
<div id="c_12"><h3 class="program_theme">Espace et géométrie</h3>
    <div class="accordion">
      <h4>Présentation</h4>
      <div>
Au cycle 3, les élèves ont découvert différents objets géométriques, qui continuent
à être rencontrés au cycle 4. Ils valident désormais par le raisonnement
et la démonstration les propriétés qu'ils conjecturent. Les définitions
et propriétés déjà vues au cycle 3 ainsi que les nouvelles propriétés
introduites au cycle 4 (relations entre angles et parallélisme,
somme des angles d'un triangle, inégalité triangulaire, caractérisation
de la médiatrice, théorèmes de Thalès et de Pythagore) fournissent un
éventail d'outils nourrissant la mise en &oelig;uvre d'un raisonnement.
Les transformations font l'objet d'une première approche, consistant à
observer leur effet sur des configurations planes, notamment au moyen d'un
logiciel de géométrie.</div>
    </div>

<h4></h4><ul class="program_submenu"><li><a href="#c_13">Représenter l'espace</a></li><li><a href="#c_14">Utiliser les notions de géométrie plane pour démontrer</a></li></ul><div id="c_13"><h4 class="program_titre">Représenter l'espace</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">(Se) repérer sur une droite graduée, dans le plan muni d'un repère orthogonal, dans un parallélépipède rectangle ou sur une sphère.
<ul><li>Abscisse, ordonnée, altitude.
</li><li>Latitude, longitude.</li></ul>

Utiliser, produire et mettre en relation des représentations de solides et de situations spatiales.
<br class="spacer">Développer sa vision de l'espace.</td>
<td class="program_modalites">Repérer une position sur carte à partir de ses coordonnées géographiques.
<br class="spacer">
Mettre en relation diverses représentations de solides (par exemple, vue en
perspective, vue de face, vue de dessus, vue en coupe) ou de situations
spatiales (par exemple schémas, croquis, maquettes, patrons, figures
géométriques).
<br class="spacer">
Utiliser des solides concrets (en carton par exemple) pour illustrer certaines
propriétés.
<br class="spacer">
Utiliser un logiciel de géométrie pour visualiser des solides et leurs sections
planes afin de développer la vision dans l'espace. Faire le lien avec les
courbes de niveau sur une carte.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_14"><h4 class="program_titre">Utiliser les notions de géométrie plane pour démontrer</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Mettre en &oelig;uvre ou écrire un protocole de construction d'une figure géométrique.
<br class="spacer">
Coder une figure.
<br class="spacer">
Comprendre l'effet d'une translation, d'une symétrie (axiale et centrale), d'une
rotation, d'une homothétie sur une figure.</td>
<td class="program_modalites">Construire des frises, des pavages, des rosaces.
<br class="spacer">Utiliser un logiciel de géométrie dynamique, notamment pour transformer une figure par translation, symétrie, rotation, homothétie.
<br class="spacer">Faire le lien entre parallélisme et translation, cercle et rotation.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">Résoudre des problèmes de géométrie plane, prouver un résultat général, valider ou réfuter une conjecture.
<ul><li>Position relative de deux droites dans le plan.
</li><li>Caractérisation angulaire du parallélisme, angles alternes / internes.
</li><li>
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/geometry/fr/perpendicular_bisector&+cmd=new Médiatrice d'un segment
.
</li><li>Triangle : somme des angles, inégalité triangulaire, cas d'égalité des triangles, triangles semblables,
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/geometry/fr/altitude&+cmd=new hauteurs
, rapports trigonométriques dans le triangle rectangle (
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/analysis/fr/sinus&+cmd=new sinus
,
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/analysis/fr/cosinus&+cmd=new cosinus
,
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/analysis/fr/trigo_tangent&+cmd=new tangente
).
</li><li>Parallélogramme : propriétés relatives aux côtés et aux diagonales.
</li><li>Théorème de Thalès et réciproque.
</li><li>
!href target=wims_gloss module=adm/tool/glossary&+special_parm=mathematics/geometry/fr/pythagore&+cmd=new Théorème de Pythagore
 et réciproque.</li></ul></td>
<td class="program_modalites">Distinguer un résultat de portée générale d'un cas particulier observé sur une figure.
<br class="spacer">
Faire le lien entre théorème de Thalès, homothétie et proportionnalité.
<br class="spacer">
Utiliser la trigonométrie du triangle rectangle pour calculer des longueurs ou des angles.
<br class="spacer">
Démontrer, par exemple, que des droites sont parallèles ou perpendiculaires,
qu'un point est le milieu d'un segment, qu'une droite est la médiatrice d'un
segment, qu'un quadrilatère est un parallélogramme, un rectangle, un losange ou
un carré.
<br class="spacer">
Etudier comment les notions de la géométrie plane ont permis de déterminer des
distances astronomiques (estimation du rayon de la Terre par Eratosthène,
distance de la Terre à la Lune par Lalande et La Caille, etc...).</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table>
        </div> <!-- close titre -->
      <div class="accordion">
        <h4>Repères de progressivité</h4>
        <div>
Les problèmes de construction constituent un champ privilégié de l'activité géométrique tout au long du cycle 4. Ces problèmes, diversifiés dans leur nature et la connexion qu'ils entretiennent avec différents champs mathématiques, scientifiques, technologiques ou artistiques, sont abordés avec les instruments de tracé et de mesure. Dans la continuité du cycle 3, les élèves se familiarisent avec les fonctionnalités d'un logiciel de géométrie dynamique ou de programmation pour construire des figures.
<br class="spacer">
La pratique des figures usuelles et de leurs propriétés, entamée au cycle 3, est
poursuivie et enrichie dès le début et tout au long du cycle 4, permettant aux
élèves de s'entraîner au raisonnement et de s'initier petit à petit à la
démonstration.
<br class="spacer">
Le théorème de Pythagore est introduit dès la 4<sup>e</sup>, et est réinvesti
tout au long du cycle dans des situations variées du plan et de l'espace. Le
théorème de Thalès est introduit en 3<sup>e</sup>, en liaison étroite avec la
proportionnalité et l'homothétie, mais aussi les agrandissements et réductions.
<br class="spacer">
La symétrie axiale a été introduite au cycle 3. La symétrie centrale est
travaillée dès le début du cycle 4, en liaison avec le parallélogramme. Les
translations, puis les rotations sont introduites en milieu de cycle, en liaison
avec l'analyse ou la construction des frises, pavages et rosaces, mais sans
définition formalisée en tant qu'applications ponctuelles. Une fois ces notions
consolidées, les homothéties sont amenées en 3<sup>e</sup>, en lien avec les
configurations de Thalès, la proportionnalité, les fonctions linéaires, les
rapports d'agrandissement ou de réduction des grandeurs géométriques.</div>
      </div>
</div> <!-- close theme -->
<div id="c_15"><h3 class="program_theme">Algorithmique et programmation</h3>
    <div class="accordion">
      <h4>Présentation</h4>
      <div>
Au cycle 4, les élèves s'initient à la programmation, en développant dans une démarche de projet quelques programmes simples, sans viser une connaissance experte et exhaustive d'un langage ou d'un logiciel particulier. En créant un programme, ils développent des méthodes de programmation, revisitent les notions de variables et de fonctions sous une forme différente, et s'entraînent au raisonnement.</div>
    </div>

<h4></h4><ul class="program_submenu"><li><a href="#c_16">Écrire, mettre au point et exécuter un programme simple</a></li></ul><div id="c_16"><h4 class="program_titre">Écrire, mettre au point et exécuter un programme simple</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Connaissances et compétences associées</th>
<th class="modalites">Exemples de situations, d'activités et de ressources pour l'élève</th></tr></thead><tbody><tr><td class="program_contenu">Décomposer un problème en sous-problèmes afin de structurer un programme ; reconnaître des schémas.
<br class="spacer">
Écrire, mettre au point (tester, corriger) et exécuter un programme en réponse
à un problème donné.
<br class="spacer">
Écrire un programme dans lequel des actions sont déclenchées par des évènements
extérieurs.
<br class="spacer">
Programmer des scripts se déroulant en parallèle.
<ul><li>Notions d'algorithme et de programme.
</li><li>Notion de variable informatique.
</li><li>Déclenchement d'une action par un événement, séquences d'instructions, boucles, instructions conditionnelles.</li></ul></td>
<td class="program_modalites">Jeux dans un labyrinthe, jeu de Pong, bataille navale, jeu de nim, tic tac toe.
<br class="spacer">
Initiation au chiffrement (Morse, chiffre de César, code ASCII...).
<br class="spacer">
Construction de tables de conjugaison, de pluriels, jeu du cadavre exquis?
<br class="spacer">
Calculs simples de calendrier.
<br class="spacer">
Calculs de répertoire (recherche, recherche inversée...).
<br class="spacer">
Calculs de fréquences d'apparition de chaque lettre dans un texte pour distinguer
sa langue d'origine : français, anglais, italien, etc...</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table>
        </div> <!-- close titre -->
      <div class="accordion">
        <h4>Repères de progressivité</h4>
        <div>
En 5<sup>e</sup>, les élèves s'initient à <a target="wims_external"href="https://magistere.education.fr/reseau-canope/course/view.php?id=377&pageid=4781" >la programmation événementielle</a>.
Progressivement, ils développent de nouvelles compétences,
en programmant des actions en parallèle, en utilisant la notion de variable informatique,
en découvrant les boucles et les instructions conditionnelles qui complètent les
structures de contrôle liées aux évènements.</div>
      </div>
</div> <!-- close theme -->
<div id="c_17"><h3 class="program_theme">Croisements entre enseignements</h3>

<h4></h4><ul class="program_submenu"><li><a href="#c_18">Corps, santé, bien-être et sécurité</a></li><li><a href="#c_19">Culture et création artistiques</a></li><li><a href="#c_20">Transition écologique et développement durable</a></li><li><a href="#c_21">Information, communication, citoyenneté</a></li><li><a href="#c_22">Langues et cultures de l'Antiquité</a></li><li><a href="#c_23">Sciences, technologie et société.</a></li></ul><div id="c_18"><h4 class="program_titre">Corps, santé, bien-être et sécurité</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Autres disciplines</th>
<th class="modalites">Mathématiques</th></tr></thead><tbody><tr><td class="program_contenu">En lien avec l'éducation physique et sportive, les sciences de la vie et de la Terre, la chimie, la technologie.
<br/><strong>Sport et sciences ; alimentation et entraînement ; physiologie de l'effort et performances.</strong></td>
<td class="program_modalites">Statistiques, proportionnalité, représentation de données, vitesse.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec les sciences de la vie et de la Terre, l'éducation physique et sportive
<br/><strong>Rythmes circadiens, fréquences respiratoires, fréquences cardiaques.</strong></td>
<td class="program_modalites">Relevé, interprétation des données ; mesure de durées, fréquences.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec les sciences de la vie et de la Terre, la géographie.
<br/><strong>Les séismes et raz-de-marée.</strong></td>
<td class="program_modalites">Proportionnalité, échelles, vitesse.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_19"><h4 class="program_titre">Culture et création artistiques</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Autres disciplines</th>
<th class="modalites">Mathématiques</th></tr></thead><tbody><tr><td class="program_contenu">En lien avec les arts plastiques, la technologie, le français.
<br/><strong>L'architecture, art, technique et société.</strong></td>
<td class="program_modalites">Proportionnalité, agrandissement réduction, géométrie.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec les arts plastiques, l'histoire.
<br/><strong>Les représentations en perspectives.</strong></td>
<td class="program_modalites">Perspectives parallèles ; expérience de Brunelleschi.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec l'histoire, les sciences (sciences de la vie et de la Terre, physique-chimie), les arts plastiques.
<br/><strong>Les relations entre arts et sciences dans la civilisation médiévale musulmane.</strong></td>
<td class="program_modalites">Translations, symétries, figures géométriques, frises et pavages.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_20"><h4 class="program_titre">Transition écologique et développement durable</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Autres disciplines</th>
<th class="modalites">Mathématiques</th></tr></thead><tbody><tr><td class="program_contenu">En lien avec la géographie, la technologie, les sciences de la vie et de la Terre.
<br/><strong>L'aménagement du territoire.</strong></td>
<td class="program_modalites">Cartes ; réduction, agrandissement.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec la physique-chimie, les sciences de la vie et de la Terre, l'histoire et la géographie, le français, les langues vivantes étrangères et régionales, l'éducation aux médias et à l'information.
<br/><strong>Les phénomènes météorologiques et climatiques.</strong></td>
<td class="program_modalites">Différentes échelles de temps ; statistiques.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec la physique-chimie, les sciences de la vie et de la Terre, l'histoire et la géographie.
<br/><strong>Gestion des ressources naturelles.</strong></td>
<td class="program_modalites">Calcul de consommation d'eau, d'énergie... ; prix d'extraction, de production, de marché ;  grandeurs quotient et grandeurs produit.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_21"><h4 class="program_titre">Information, communication, citoyenneté</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Autres disciplines</th>
<th class="modalites">Mathématiques</th></tr></thead><tbody><tr><td class="program_contenu">En lien avec l'éducation aux médias et à l'information, la géographie, les sciences de la vie et de la Terre.
<br/><strong>L'information chiffrée et son interprétation.</strong></td>
<td class="program_modalites">Représentations, choix des échelles.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec la technologie, l'éducation aux médias et à l'information.
<br/><strong>Le stockage de l'information sur support numérique.</strong></td>
<td class="program_modalites">Calcul, puissances.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_22"><h4 class="program_titre">Langues et cultures de l'Antiquité</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Autres disciplines</th>
<th class="modalites">Mathématiques</th></tr></thead><tbody><tr><td class="program_contenu">En lien avec les langues anciennes, l'histoire, les sciences.
<br/><strong>Questions de sciences dans l'Antiquité.</strong></td>
<td class="program_modalites">Mesure de la circonférence de la Terre par Eratosthène ; racines carrées ; Thalès, Pythagore ; fractions égyptiennes ; différents systèmes et formes de numération.</td>
</tr><tr><td colspan="2" class="program_wims">

<ul class="program_ul_wims inline"><li>
!href target=wims_exo module=E6/number/oefantic.fr&exo=&+cmd=intro Numération à travers les âges
</li> </ul>
</td></tr>
</tbody></table></div> <!-- close titre -->
 <div id="c_23"><h4 class="program_titre">Sciences, technologie et société.</h4>


   <table class="wimsborder blockcenter">
   <caption style="caption-side: bottom;"></caption><thead><tr>
<th class="contenu">Autres disciplines</th>
<th class="modalites">Mathématiques</th></tr></thead><tbody><tr><td class="program_contenu">En lien avec l'histoire, les sciences et la technologie.
<br/><strong>Les théories scientifiques qui ont changé la vision du monde Ptolémée, Copernic, Galilée, Kepler.</strong></td>
<td class="program_modalites">Rotation, périodicité.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec l'histoire, les sciences et la technologie.
<br/><strong>Les sciences à l'époque de la Révolution française.</strong></td>
<td class="program_modalites">Système métrique ; méridien ; triangulation ; incertitude.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr><tr><td class="program_contenu">En lien avec la technologie, le français, l'éducation aux médias et à l'information.
<br/><strong>Réel et virtuel, de la science-fiction à la réalité.</strong></td>
<td class="program_modalites">Programmer un robot, concevoir un jeu.</td>
</tr><tr><td colspan="2" class="program_wims">

</td></tr>

</tbody></table>
</div><!-- close titre -->
</div><!-- close theme -->

</div>
!if $jquery_defined=yes
  <script>
    jQuery(function($$){
      $$(".accordion").accordion({
        collapsible: true,
        active: false,
      });
    } );
  </script>
  !read tabscript mathcycle4
!endif
!tail
