!! Copié à partir de /modules/home dans themes/widgets

!if $wims_user=$empty
<div class="small-12 cell"><!--Sur se site vous...-->
	<div class="wims_motd">
	  !read ./wimshome/log/motd.phtml.$lang
	</div>
	<div class="wims_frontpage">
	  !readproc wimshome/log/front.phtml.$lang
	  !if yes notin $front_exist
	  Est ce utile maintenant ?? Modifié le 22/6/19 par jlben
		  !if  $wims_theme=Nikaia2
		  	!read themes/$wims_theme/home//front.phtml.$lang
		  !else
		    !read ./front.phtml.$lang
		  !endif
	  !else
	    !read wimshome/log/front.phtml.$lang
	  !endif
	</div>
</div>
!endif
