<div id="lexique" class="wims_widget_box small-12 medium-6 large-4 cell ">
    <div class="title_box">
      <h2 class="wims_title">Recherche par taxonomie ou glosssaire</h2>
    </div>
	<div class="box_content">
			!set wims_ref_class=text_icon browse
	    	!href module=adm/browse $wims_name_browse
	    	<br class="clearall" />
	    	<button class="button dropdown small-dropdown" type="button" data-toggle="lexique_level_math"><span class="text_icon exomodify"></span>&nbsp;Mathématiques</button>
        	<div class="dropdown-pane" data-position="top" data-alignment="left" id="lexique_level_math" data-dropdown data-auto-focus="true">
        		<nav class ="summary">
                        <ul  class="dropdown menu vertical medium-horizontal" data-responsive-menu="accordion small-dropdown">
                            <li>
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=algebra&pref=OK Algèbre
							</li>
							<li >
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=analysis&pref=OK Analyse
							</li>
							<li >
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=arithmetic&pref=OK Arithmétique
							</li>
							<li >
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=general&pref=OK Général
							</li>
							<li >
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=geometry&pref=OK Géométrie
							</li>
							<li >
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=probability&pref=OK Probabilités
							</li>
							<li >
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=mathematics&gloss_zone=satatistics&pref=OK Statistiques
							</li>
                        </ul>
                </nav>
        	</div>
        	<button class="button dropdown small-dropdown" type="button" data-toggle="lexique_level_bio"><span class="text_icon exomodify"></span>&nbsp;Biologie</button>
        	<div class="dropdown-pane" data-position="top" data-alignment="left" id="lexique_level_bio" data-dropdown data-auto-focus="true">
        		<nav class ="summary">
                        <ul  class="dropdown menu vertical medium-horizontal" data-responsive-menu="accordion small-dropdown"
		                  	<li>
								!href module=adm/tool/glossary&gloss_lang=fr&gloss_domain=biology&gloss_zone=genetics&pref=OK Génétique
							</li>
                      	</ul>
                </nav>
        	</div>
	</div>
</div>