
<style>
	.euler_actu_list li{
		list-style:none;
	}
	.euler_actu_date p{
		color:#999;
  		font-size:10px;
	}
</style>
<div id="actualites" class="wims_widget_box cell small-12 medium-6 scroller">
    <div class="title_box">
      <h2 class="wims_title">Actualités</h2>
      <!--<br class="clearall" />-->
    </div>
    <div class="box_content">
      <div>
      	<ul class="accordion" data-responsive-accordion-tabs="accordion medium-tabs large-accordion">
        <li class="accordion-item is-active" data-accordion-item>
          <a href="#" class="accordion-title">Les dernières</a>
          <div class="accordion-content" data-tab-content >
          <ul class="euler_actu_list">
            !set nbactu=!defof nbactu in wimshome/public_html/modules/local/algebra/oefacveractualite.fr/data/blocactu
            !for numactu=1 to $nbactu
              <li>
                !record $numactu of wimshome/public_html/modules/local/algebra/oefacveractualite.fr/data/blocactu
              </li>
            !next
          </ul>
          </div>
        </li>
        <li class="accordion-item" data-accordion-item>
          <a href="#" class="accordion-title">Toutes les actualités</a>
          <div class="accordion-content" data-tab-content>
            !read ./wimshome/public_html/modules/local/algebra/oefacveractualite.fr/data/blocactu
          </div>
        </li>
      </ul>
     </div>
  </div>
</div>
<script src="html/themes/Euler/js/foundation.js"></script>
<script src="html/themes/Euler/js/app.js"></script>
