

<div id="exemples" class="wims_widget_box small-12 medium-6 cell scroller">
  <div class="title_box">
    <h2 class="wims_title">Exemples de ressources</h2>
    <!--<br class="clearall" />-->
  </div>
  
  <div class="box_content">

      !set nbslide=!defof nbslide in wimshome/public_html/modules/local/algebra/oefacveractualite.fr/data/blocexemple     
      <div class="orbit" role="region" aria-label="Exemples de ressources" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;" data-timer-delay="10000" data-auto-play="true" data-pause-on-hover="false" data-accessible="true">
          <div class="orbit-wrapper">
            <div class="orbit-controls">
              <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
              <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
            </div>
          
            <ul class="orbit-container">
              !set rec=!record 1 of wimshome/public_html/modules/local/algebra/oefacveractualite.fr/data/blocexemple
              !set diapo=!lines2items $rec
              !distribute items $diapo into path_ex,title,path_img
                <li class="is-active orbit-slide">
                  <figure class="orbit-figure">
                    <p class="euler_carousel_titre">
                      !href $path_ex $title
                    </p>
                    <img class="orbit-image" src="$path_img" alt="$title" title="$title">
                  </figure>
                </li>
                !reset rec diapo path_ex title path_img

              !for numslide=2 to $nbslide
                !set rec=!record $numslide of wimshome/public_html/modules/local/algebra/oefacveractualite.fr/data/blocexemple
                !set diapo=!lines2items $rec
                !distribute items $diapo into path_ex,title,path_img
                <li class="orbit-slide">
                  <figure class="orbit-figure">
                    <p class="euler_carousel_titre">
                      !href $path_ex $title
                    </p>
                    
                     <img class="orbit-image" src="$path_img" alt="$title" title="$title">
                  </figure>
                </li>
              !reset rec diapo path_ex title path_img
              !next
            </ul>
          </div>
          <nav class="orbit-bullets">
            <button class="is-active" data-slide="0"><span class="show-for-sr">Slide 0</span><span class="show-for-sr">Current Slide</span></button>
            !for numslide=1 to $[$nbslide-1]
            <button  data-slide="$numslide"><span class="show-for-sr">slide $numslide</span><span class="show-for-sr">Slide $numslide</span></button>
            !next
          </nav>
      </div> 
  </div>
</div>
<script src="html/themes/Nikaia2/js/foundation.js"></script>
<script src="html/themes/Nikaia2/js/app.js"></script>